name: Build and Release EXE with JSON

on:
  push:
    paths:
      - "**/*.py"
      - "**/*.json"
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest  # Use Windows to build the EXE

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      # Step 4: Build the EXE
      - name: Build the executable
        run: |
          pyinstaller --onefile resistalabel.py

      # Step 5: Create ZIP file with EXE, JSON, and Font
      - name: Package EXE, JSON, and Font into ZIP
        run: |
          mkdir release
          mv dist/resistalabel.exe release/
          cp resistor_values.json release/
          cp resistor_values_example.json release/
          cp Roboto-Bold.ttf release/
          cd release
          powershell -Command "Compress-Archive -Path * -DestinationPath ../resistalabel.zip"

      # Step 6: Create GitHub Release and Upload ZIP
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: resistalabel.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
