name: Build and Release EXE with JSON

on:
  push:
    paths:
      - "**/*.py"
      - "**/*.json"
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Read and Increment Version
      - name: Read and Increment Version
        id: versioning
        shell: pwsh
        run: |
          $current_version = Get-Content version.txt
          Write-Output "Current version: $current_version"
          $base_version = $current_version -replace 'v', ''
          $new_version = 'v' + ([math]::Round(($base_version + 0.01), 2).ToString("F2"))
          Write-Output "New version: $new_version"
          Set-Content version.txt $new_version
          echo "new_version=$new_version" >> $env:GITHUB_ENV

      # Step 3: Commit Updated Version
      - name: Commit Updated Version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add version.txt
          git commit -m "Increment version to ${{ env.new_version }}"
          git push

      # Step 4: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 5: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      # Step 6: Build the EXE
      - name: Build the executable
        run: |
          pyinstaller --onefile resistalabel.py

      # Step 7: Create ZIP file with EXE, JSON, and Font
      - name: Package EXE, JSON, and Font into ZIP
        run: |
          mkdir release
          mv dist/resistalabel.exe release/
          cp resistor_values.json release/
          cp resistor_values_example.json release/
          cp Roboto-Bold.ttf release/
          cd release
          powershell -Command "Compress-Archive -Path * -DestinationPath ../resistalabel.zip"

      # Step 8: Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.new_version }}
          name: Release ${{ env.new_version }}
          files: resistalabel.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
